apiVersion: batch/v1
kind: Job
metadata:
  name: createdb
  namespace: industryfusion
spec:
  template:
    spec:
      containers:
      - name: postgres
        image: postgres:10.4
        env:
        - name: POSTGRES_DB
          value: postgresdb
        - name: POSTGRES_USER
          value: postgres
        - name: PGPASSWORD
          value: postgres
        command: ["/bin/sh","-c"]
        args: ["/usr/bin/psql postgresql://${POSTGRES_USER}:${PGPASSWORD}@postgres:5432/${POSTGRESDB} -f /tmp/ddl.sql && echo Now deploying demoinserts && /usr/bin/psql postgresql://${POSTGRES_USER}:${PGPASSWORD}@postgres:5432/${POSTGRES_DB} -f /tmp/sampleinserts.sql"]
        volumeMounts:
        - name: config
          mountPath: /tmp
      restartPolicy: Never
      imagePullSecrets:
        - name: dockercred
      volumes:
        - name: config
          configMap:
            name: if-config
            items:
            - key: sampleinserts.sql
              path: sampleinserts.sql
            - key: demoinserts.sql
              path: demoinserts.sql
            - key: ddl.sql
              path: ddl.sql
  backoffLimit: 10
