apiVersion: v1
kind: Service
metadata:
  labels:
    app: hbase-master
  name: hbase-master
spec:
  clusterIP: None
  ports:
  - name: "8080"
    port: 8080
  - name: "9090"
    port: 9090
  - name: "9095"
    port: 9095
  - name: "16010"
    port: 16010
  - name: "60000"
    port: 60000
  - name: "webui"
    port: 60010
  - name: "2181"
    port: 2181
  selector:
    app: hbase-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-master
  labels:
    app: hbase-master
spec:
  serviceName: hbase-master
  replicas: 1
  selector:
    matchLabels:
      app: hbase-master
  template:
    metadata:
      labels:
        app: hbase-master
    spec:
      containers:
      - name: hbase-master
        image: oisp/hbase:nightly-2020-01-25
        resources:
          {{ if .Values.less_resources }}
          requests:
            cpu: 50m
          {{ else }}
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 500m
            memory: 1G
          {{ end }}
        env:
        - name: REGIONSERVERS
          value: {{ .Values.hbaseScale.regionServers }}
        - name: ZOOKEEPER
          value: zookeeper
        - name: HDFS_NAMENODE
          value: hdfs-namenode
        - name: HADOOP_USER_NAME
          value: root
        command: ["/bin/bash", "/opt/wait-for-it.sh", "hdfs-namenode:8020", "-t", "300", "--", "bash", "/opt/wait-for-it.sh", "zookeeper:2181", "-t", "300", "--", "/opt/entrypoint.sh"]
        ports:
        - containerPort: 2181
        - containerPort: 9090
        - containerPort: 60000
        - containerPort: 60010
        - containerPort: 60020
        - containerPort: 16000
        - containerPort: 16010
      imagePullSecrets:
      - name: dockercred
