apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: {{ .Values.zookeeper.name }}
spec:
  {{ if .Values.less_resources }}
  replicas: 1
  {{ else }}
  replicas: 3
  {{ end }}
