server:
  error:
    include-stacktrace: never

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://postgres:5432/postgresdb
    username: postgresadmin
    password: posgresadminpw
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    database: postgresql

logging:
  level:
    root: INFO

