-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- company
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'Industry Business Network 4.0 e.V.', 'ibn_logo.png', 'Industry Business Network 4.0', 'ECOSYSTEM_MANAGER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'SmartFactory@IBN4.0', 'ibn_logo.png', 'IBN 4.0 Smart Factory', 'MACHINE_CUSTOMER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'MicroStep Europa GmbH', 'microstep_logo.png', 'MicroStep', 'MACHINE_MANUFACTURER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'TEKA Absaug- und Entsorgungstechnologie GmbH', 'teka_logo.png', 'TEKA', 'MACHINE_MANUFACTURER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'IBEDA Sicherheitsgeräte und Gastechnik GmbH & Co. KG', 'ibeda_logo.png', 'Ibeda', 'MACHINE_MANUFACTURER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'ARKU Maschinenbau GmbH', 'arku_logo.png', 'Arku', 'MACHINE_MANUFACTURER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'Beuting Metalltechnik GmbH & Co. KG', 'beuting_logo.png', 'Beuting', 'MACHINE_MANUFACTURER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'Eckert AS Sp. z o. o.', 'eckert_logo.png', 'Eckert', 'MACHINE_MANUFACTURER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'Kjellberg Finsterwalde Plasma und Maschinen GmbH', 'kjellberg_logo.png', 'Kjellberg', 'MACHINE_MANUFACTURER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'Novus air GmbH', 'novus_logo.png', 'Novus', 'MACHINE_MANUFACTURER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'Rösler Oberflächentechnik GmbH', 'roesler_logo.png', 'Rösler', 'MACHINE_MANUFACTURER');
insert into company (id, version, description, image_key, name, type) values (nextval('idgen_company'), 0, 'LISSMAC Maschinenbau GmbH', 'lissmac_logo.png', 'Lissmac', 'MACHINE_MANUFACTURER');
-- location
insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Bad Wörishofen', 'Germany', 'microstep_standort_1.jpg', 48.019610, 'Rudolf-Diesel-Straße 16', '', 10.603630, 'MicroStep', 'HEADQUARTER', '86825', 2);
-- insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Dorsten', 'Germany', 'microstep_standort_1.jpg', 51.677480, 'Wenger Höfe 27', '', 6.997910, 'MicroStep - CompetenceCenter Nord', 'FABRICATION', '46284', 2);
insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Goldach', 'Switzerland', 'stuermsfs_standort_1.jpg', 47.482330, 'Langrütistrasse 20', '', 9.476290, 'Stürmsfs', 'FABRICATION', '9403', 2);
insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Neustadt (Wied)', 'Germany', 'ibeda_standort_1.jpg', 50.62504, 'Bahnhofstraße 27', '', 7.43335, 'Ibeda', 'FABRICATION', '53577', 2);
-- insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Velen', 'Germany', 'teka_standort_1.jpg', 51.895374, 'Industriestraße 13', '', 6.997759, 'Teka - Smart Factory', 'FABRICATION', '46342', 2);
insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Baden-Baden', 'Germany', 'arku_standort_1.jpg', 48.812312, 'Siemensstrasse 11', '', 8.217716, 'ARKU', 'HEADQUARTER', '76532', 2);
-- insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Legnica', 'Poland', 'eckert_standort_1.jpg', 51.231556, 'Pawicka 4C', '', 16.200273, 'Eckert - Smart Factory', 'FABRICATION', '59-220', 2);
-- insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Finsterwalde', 'Germany', 'kjellberg_standort_1.jpg', 51.627571, 'Oscar-Kjellberg-Straße 20', '', 13.705277, 'Kjellberg - Smart Factory', 'FABRICATION', '03238', 2);
insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Weinböhla', 'Germany', 'novus_standort_1.jpg', 51.14999, 'Zur alten Elektrowärme 9', '', 13.54230, 'Novus air', 'FABRICATION', '01689', 2);
-- insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Untermerzbach', 'Germany', 'roesler_standort_1.jpg', 50.141405, 'Vorstadt 1', '', 10.853232, 'Rösler - Smart Factory', 'FABRICATION', '96190', 2);
insert into location (id, version, city, country, image_key, latitude, line1, line2, longitude, name, type, zip, company_id) values (nextval('idgen_location'), 0, 'Bad Wurzach', 'Germany', 'lissmac_standort_1.jpg', 47.9081917, 'Lanzstraße 4', '', 9.8938287, 'Lissmac', 'FABRICATION', '88410', 2);

-- room
insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Showroom', 'Showroom', 1);
insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Technikraum', 'Technikraum', 1);
insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Halle 3 Brennbetrieb', 'Halle 3 Brennbetrieb', 2);
insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Showroom', 'Showroom', 3);
insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Lohnarbeitszentrum', 'Lohnarbeitszentrum', 4);
insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Produktionshalle', 'Produktionshalle', 5);
insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Application Center', 'Application Center', 6);
-- insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Showroom', 'Showroom', 7);
-- insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Showroom', 'Showroom', 8);
-- insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Showroom', 'Showroom', 9);
-- insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Showroom', 'Showroom', 10);
-- insert into room (id, version, image_key, name, description, location_id) values (nextval('idgen_room'), 0, null, 'Showroom', 'Showroom', 11);

-- quantity_type
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Duration Quantity', 'duration', 'Duration', 1);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Length Quantity', 'length', 'Length', 0);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Text', 'text', 'Text', 0);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Pressure Quantity', 'pressure', 'Pressure', 1);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Airflow Quantity', 'airflow', 'Airflow', 1);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Electrical Current Quantity', 'electric_current', 'Electric Current', 1);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Relative Humidity Quantity', 'relative_humidity', 'Relative Humidity', 1);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Noise Quantity', 'noise', 'Noise', 1);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Particle Density Quantity', 'particle_density', 'Particle Density', 1);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Temperature Quantity', 'temperature', 'Temperature', 1);
insert into quantity_type (id, version, description, label, name, data_type) values (nextval('idgen_quantitytype'), 0, 'Rotational Speed Quantity', 'rotational_speed', 'Rotational Speed', 1);
-- unit
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Duration: Seconds', 'seconds', 'Seconds', 's', 1);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Duration: Years', 'years', 'Years', 'y', 1);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Length: Millimeter', 'mm', 'Millimeter', 'mm', 2);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Text', 'text', 'Text', '', 3);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Duration Hours', 'hours', 'Hours', 'h', 1);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Pressure: Millibar', 'millibar', 'Millibar', 'mbar', 4);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Air consumption: Liters', 'liters', 'Liters', 'l', 5);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Current: Ampere', 'ampere', 'Ampere', 'A', 6);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Pressure: Bar', 'bar', 'Bar', 'bar', 4);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Relative Humidity: Percent', 'relative_humidity_percent', 'Percent', '%', 7);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Noise: dB', 'noise_db', 'Decibel', 'dB', 8);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Particle Density: Density mg/m³', 'milligram_per_cubicmeter', 'Milligram per Cubic Meter', 'mg/m³', 9);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Temperature: C', 'degrees_celsius', 'Degrees Celsius', '°C', 10);
insert into unit (id, version, description, label, name, symbol, quantity_type_id) values (nextval('idgen_unit'), 0, 'Rotational Speed: 1/s', 'revolutions_per_second', 'Revolutions per Second', '1/s', 11);
-- quantity_type.base_unit_id
update quantity_type set base_unit_id = 1 where id = 1;
update quantity_type set base_unit_id = 3 where id = 2;
update quantity_type set base_unit_id = 4 where id = 3;
update quantity_type set base_unit_id = 6 where id = 4;
update quantity_type set base_unit_id = 7 where id = 5;
update quantity_type set base_unit_id = 8 where id = 6;
update quantity_type set base_unit_id = 10 where id = 7;
update quantity_type set base_unit_id = 11 where id = 8;
update quantity_type set base_unit_id = 12 where id = 9;
update quantity_type set base_unit_id = 13 where id = 10;
update quantity_type set base_unit_id = 14 where id = 11;
-- field
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 1, 'Maintenance interval', 'maintenance_interval', 'Maintenance interval', null, 5);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 0, 'Asset status', 'status', 'Asset status', null, 4);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 0, 'Cutting program', 'cutting_program', 'Cutting program', null, 4);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 1, 'Total cutting time', 'total_cutting_time', 'Total cutting time', null, 1);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 1, 'Remaining cutting time', 'remaining_cutting_time', 'Remaining cutting time', null, 1);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 0, 'Material name', 'material_name', 'Material name', null, 4);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 0, 'Material specification', 'material_spec', 'Material specification', null, 4);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 1, 'Plate thickness', 'plate_thickness', 'Plate thickness', null, 3);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 1, 'Hours till maintenance', 'hours_til_mantenance', 'Hours till maintenance', null, 5);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Differential pressure', 'differential_pressure', 'Differential pressure', null, 6);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Low pressure', 'low_pressure', 'Low pressure', null, 6);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Air consumption', 'air_consumption', 'Air consumption', null, 7);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Air pressure', 'air_pressure', 'Air pressure', null, 9);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Pressure bottle', 'pressure_bottle', 'Pressure bottle', null, 9);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Pressure pipe', 'pressure_pipe', 'Pressure pipe', null, 9);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Electrical current', 'electric_current', 'Electrical current', null, 8);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Pressure takeoff', 'pressure_takeoff_1', 'Pressure takeoff', null, 9);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Humidity', 'Humidity', 'Humidity', null, 10);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Noise', 'Noise', 'Noise', null, 11);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Dust', 'Dust', 'Dust', null, 12);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Temperature', 'Temperature', 'Temperature', null, 13);
insert into field (id, version, accuracy, description, label, name, value, unit_id) values (nextval('idgen_field'), 0, 2, 'Rotational Speed', 'Rotational Speed', 'Rotational Speed', null, 14);
-- asset_type
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'CNC-Laserschneidanlage', 'laserschneidanlage', 'Laserschneidanlage');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'Stationäre Staubfilteranlage', 'filteranlage', 'Filteranlage');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'Gasversorgungsanlage', 'gasversorgung', 'Gasversorgungsanlage');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'CNC-Plasmaschneidanlage', 'plasmaschneidanlage', 'Plasmaschneidanlage');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'Plasmastromquelle', 'plasmastromquelle', 'Plasmastromquelle');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'Strahlanlage', 'strahlanlage', 'Strahlanlage');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'Richtmaschine', 'richtmaschine', 'Richtmaschine');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'Raumluftüberwachungssystem', 'raumluftüberwachung', 'Raumluftüberwachung');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'Entgratmaschine', 'entgratmaschine', 'Entgratmaschine');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'Oberflächenbearbeitungsmaschine', 'oberflächenbearbeitungsmaschine', 'Oberflächenbearbeitungsmaschine');
insert into asset_type (id, version, description, label, name) values (nextval('idgen_assettype'), 0, 'Gasmischer', 'gasmischer', 'Gasmischer');

-- asset_type_template
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'CNC-Laserschneidanlage', '', 'Laserschneidanlage', 1);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'Stationäre Staubfilteranlage', '', 'Filteranlage', 2);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'Gasversorgungsanlage', '', 'Gasversorgung', 3);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'CNC-Plasmaschneidanlage', '', 'Plasmaschneidanlage', 4);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'Plasmastromquelle', '', 'Plasmastromquelle', 5);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'Strahlanlage', '', 'Strahlanlage', 6);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'Richtmaschine', '', 'Richtmaschine', 7);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'Raumluftüberwachungssystem', '', 'Raumluftüberwachung', 8);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'Entgratmaschine', '', 'Entgratmaschine', 9);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'Oberflächenbearbeitungsmaschine', '', 'Oberflächenbearbeitungsmaschine', 10);
insert into asset_type_template (id, version, description, image_key, name, asset_type_id) values (nextval('idgen_assettypetemplate'), 0, 'Gasmischer', '', 'Gasmischer', 11);
-- field_target
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 0, 'maintenance_interval', true, 'Maintenance interval', 1, 1);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'status', true, 'Asset status', 1, 2);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'cutting_program', true, 'Cutting program', 1, 3);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'total_cutting_time', true, 'Total cutting time', 1, 4);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'remaining_cutting_time', true, 'Remaining cutting time', 1, 5);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'material_name', true, 'Material name', 1, 6);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'material_specification', true, 'Material specification', 1, 7);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'plate_thickness', true, 'Plate thickness', 1, 8);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'hours_maintenance', true, 'Hours till maintenance', 1, 9);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 0, 'maintenance_interval', true, 'Maintenance interval', 2, 1);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'status', true, 'Asset status', 2, 2);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'differential_pressure', true, 'Differential pressure', 2, 10);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'low_pressure', true, 'Low pressure', 2, 11);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'air_consumption', true, 'Air consumption', 2, 12);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'air_pressure', true, 'Air pressure', 2, 13);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'electric_current', true, 'Electric current', 2, 16);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'hours_maintenance', true, 'Hours till maintenance', 2, 9);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 0, 'maintenance_interval', true, 'Maintenance interval', 3, 1);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'status', true, 'Asset status', 3, 2);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'pressure_bottle_left', true, 'Pressure bottle left', 3, 14);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'pressure_bottle_right', true, 'Pressure bottle right', 3, 14);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'pressure_pipe', true, 'Pressure pipe', 3, 15);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'pressure_takeoff_1', true, 'Pressure takeoff 1', 3, 17);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'hours_maintenance', true, 'Hours till maintenance', 3, 9);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 0, 'maintenance_interval', true, 'Maintenance interval', 4, 1);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'status', true, 'Asset status', 4, 2);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'cutting_program', true, 'Cutting program', 4, 3);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'total_cutting_time', true, 'Total cutting time', 4, 4);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'remaining_cutting_time', true, 'Remaining cutting time', 4, 5);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'material_name', true, 'Material name', 4, 6);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'material_specification', true, 'Material specification', 4, 7);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'plate_thickness', true, 'Plate thickness', 4, 8);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'hours_maintenance', true, 'Hours till maintenance', 4, 9);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'status', true, 'Asset status', 5, 2);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'status', true, 'Asset status', 6, 2);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_1_electric_current', true, 'Turbine 1 Electric current', 6, 16);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_1_rotational_speed', true, 'Turbine 1 Rotational Speed', 6, 22);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_2_electric_current', true, 'Turbine 2 Electric current', 6, 16);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_2_rotational_speed', true, 'Turbine 2 Rotational Speed', 6, 22);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_3_electric_current', true, 'Turbine 3 Electric current', 6, 16);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_3_rotational_speed', true, 'Turbine 3 Rotational Speed', 6, 22);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_4_electric_current', true, 'Turbine 4 Electric current', 6, 16);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_4_rotational_speed', true, 'Turbine 4 Rotational Speed', 6, 22);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_5_electric_current', true, 'Turbine 5 Electric current', 6, 16);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_5_rotational_speed', true, 'Turbine 5 Rotational Speed', 6, 22);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_6_electric_current', true, 'Turbine 6 Electric current', 6, 16);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'turbine_6_rotational_speed', true, 'Turbine 6 Rotational Speed', 6, 22);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'status', true, 'Asset status', 7, 2);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'humidity', true, 'Humidity', 8, 18);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'noise', true, 'Noise', 8, 19);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'dust', true, 'Dust', 8, 20);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'temperature', true, 'Temperature', 8, 21);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'status', true, 'Asset status', 4, 2);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'cutting_program', true, 'Cutting program', 4, 3);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'total_cutting_time', true, 'Total cutting time', 4, 4);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'remaining_cutting_time', true, 'Remaining cutting time', 4, 5);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'material_name', true, 'Material name', 4, 6);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'material_specification', true, 'Material specification', 4, 7);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'plate_thickness', true, 'Plate thickness', 4, 8);
insert into field_target (id, version, field_type, label, mandatory, name, asset_type_template_id, field_id) values (nextval('idgen_fieldtarget'), 0, 1, 'hours_maintenance', true, 'Hours till maintenance', 4, 9);
update field_target set description = name;
-- asset_series
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'MSF', '', 'MSF', true, '', '1', '', 1, 3);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'ZPF', '', 'ZPF', true, '', '5', '', 2, 4);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'Gasversorgung aus 2x2 Sauerstoffflaschen', '', 'Gasversorgung 2x2 ', true, '', '6', '', 3, 5);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'MG', '', 'MG', true, '', '1', '', 4, 3);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'Q', '', 'Q', true, '', '1', '', 5, 9);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'RRB', '', 'RRB', true, '', '1', '', 6, 11);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'FlatMaster', '', 'FlatMaster', true, '', '1', '', 7, 6);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'SBM-L', '', 'SBM-L', true, '', '1', '', 9, 12);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'PFM', '', 'PFM', true, '', '5', '', 2, 7);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'Airtracker', '', 'Airtracker', true, '', '5', '', 8, 4);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'MCC', '', 'MCC', true, '', '1', '', 4, 3);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'SMD', '', 'SMD', true, '', '1', '', 10, 12);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'iMixproVario', '', 'iMixproVario', true, '', '6', '', 11, 5);
insert into asset_series (id, version, description, image_key, name, ce_certified, handbook_key, protection_class, video_key, asset_type_template_id, company_id) values (nextval('idgen_assetseries'), 0, 'Airline', '', 'Airline', true, '', '5', '', 2, 10);

-- field_source
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Maintenance interval', 'Maintenance interval', 'maintenance_interval', null, 1, 1, 5);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Asset status', 'Asset status', 'status', null, 1, 2, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Cutting program', 'Cutting program', 'cutting_program', null, 1, 3, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Total cutting time', 'Total cutting time', 'total_cutting_time', null, 1, 4, 1);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Remaining cutting time', 'Remaining cutting time', 'remaining_cutting_time', null, 1, 5, 1);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Material name', 'Material name', 'material_name', null, 1, 6, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Material specification', 'Material specification', 'material_specification', null, 1, 7, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Plate thickness', 'Plate thickness', 'plate_thickness', null, 1, 8, 3);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Hours till maintenance', 'Hours till maintenance', 'hours_maintenance', null, 1, 9, 5);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Maintenance interval', 'Maintenance interval', 'maintenance_interval', null, 2, 10, 5);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Asset status', 'Asset status', 'status', null, 2, 11, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Differential pressure', 'Differential pressure', 'differential_pressure', null, 2, 12, 6);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Low pressure', 'Low pressure', 'low_pressure', null, 2, 13, 6);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Air consumption', 'Air consumption', 'air_consumption', null, 2, 14, 7);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Air pressure', 'Air pressure', 'air_pressure', null, 2, 15, 9);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Electric current', 'Electric current', 'electric_current', null, 2, 16, 8);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Hours till maintenance', 'Hours till maintenance', 'hours_maintenance', null, 2, 17, 5);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Maintenance interval', 'Maintenance interval', 'maintenance_interval', null, 3, 18, 5);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Asset status', 'Asset status', 'status', null, 3, 19, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Pressure bottle left', 'Pressure bottle left', 'pressure_bottle_left', null, 3, 20, 9);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Pressure bottle right', 'Pressure bottle right', 'pressure_bottle_right', null, 3, 21, 9);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Pressure pipe', 'Pressure pipe', 'pressure_pipe', null, 3, 22, 9);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Pressure takeoff 1', 'Pressure takeoff 1', 'pressure_takeoff_1', null, 3, 23, 9);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Hours till maintenance', 'Hours till maintenance', 'hours_maintenance', null, 3, 24, 5);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Maintenance interval', 'Maintenance interval', 'maintenance_interval', null, 4, 25, 5);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Asset status', 'Asset status', 'status', null, 4, 26, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Cutting program', 'Cutting program', 'cutting_program', null, 4, 27, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Total cutting time', 'Total cutting time', 'total_cutting_time', null, 4, 28, 1);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Remaining cutting time', 'Remaining cutting time', 'remaining_cutting_time', null, 4, 29, 1);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Material name', 'Material name', 'material_name', null, 4, 30, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Material specification', 'Material specification', 'material_specification', null, 4, 31, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Plate thickness', 'Plate thickness', 'plate_thickness', null, 4, 32, 3);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Hours till maintenance', 'Hours till maintenance', 'hours_maintenance', null, 4, 33, 5);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Asset status', 'Asset status', 'status', null, 5, 34, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Asset status', 'Asset status', 'status', null, 6, 35, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 1 Electric current', 'Turbine 1 Electric current', 'turbine_1_electric_current', null, 6, 36, 8);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 1 Rotational speed', 'Turbine 1 Rotational speed', 'turbine_1_rotational_speed', null, 6, 37, 14);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 2 Electric current', 'Turbine 2 Electric current', 'turbine_2_electric_current', null, 6, 38, 8);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 2 Rotational speed', 'Turbine 2 Rotational speed', 'turbine_2_rotational_speed', null, 6, 39, 14);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 3 Electric current', 'Turbine 3 Electric current', 'turbine_3_electric_current', null, 6, 40, 8);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 3 Rotational speed', 'Turbine 3 Rotational speed', 'turbine_3_rotational_speed', null, 6, 41, 14);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 4 Electric current', 'Turbine 4 Electric current', 'turbine_4_electric_current', null, 6, 42, 8);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 4 Rotational speed', 'Turbine 4 Rotational speed', 'turbine_4_rotational_speed', null, 6, 43, 14);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 5 Electric current', 'Turbine 5 Electric current', 'turbine_5_electric_current', null, 6, 44, 8);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 5 Rotational speed', 'Turbine 5 Rotational speed', 'turbine_5_rotational_speed', null, 6, 45, 14);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 6 Electric current', 'Turbine 6 Electric current', 'turbine_6_electric_current', null, 6, 46, 8);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Turbine 6 Rotational speed', 'Turbine 6 Rotational speed', 'turbine_6_rotational_speed', null, 6, 47, 14);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Asset status', 'Asset status', 'status', null, 7, 48, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Humidity', 'Humidity', 'humidity', null, 10, 49, 10);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Noise', 'Noise', 'noise', null, 10, 50, 11);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Dust', 'Dust', 'dust', null, 10, 51, 12);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Temperature', 'Temperature', 'temperature', null, 10, 52, 13);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Asset status', 'Asset status', 'status', null, 11, 53, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Cutting program', 'Cutting program', 'cutting_program', null, 11, 54, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Total cutting time', 'Total cutting time', 'total_cutting_time', null, 11, 55, 1);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Remaining cutting time', 'Remaining cutting time', 'remaining_cutting_time', null, 11, 56, 1);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Material name', 'Material name', 'material_name', null, 11, 57, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Material specification', 'Material specification', 'material_specification', null, 11, 58, 4);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Plate thickness', 'Plate thickness', 'plate_thickness', null, 11, 59, 3);
insert into field_source (id, version, description, name, source_sensor_label, value, asset_series_id, field_target_id, source_unit_id) values (nextval('idgen_fieldsource'), 0, 'Hours till maintenance', 'Hours till maintenance', 'hours_maintenance', null, 11, 60, 5);


-- asset
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, ' CNC-Laser Cutting Machine', 'microstep_asset_msf.jpg', 'MSF Compact 1001.20L', true, '2019-10-11 00:00:00.000000', 'CNC', 'lasercutter', 'SQL', 'f06ec371-68e9-404e-8cf5-1c8da37ecb3d', null, true, '2019-10-18 00:00:00.000000', '1', '2551', null, 1, 2, 1);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'Filteranlage', 'teka_asset_zpf.jpg', 'ZPF 6H', true, '2017-10-11 00:00:00.000000', 'PLC S7-1200', 'filteringunit', 'PLC', '3a3040fc-3fd5-4cc2-ad98-b9d4e82902f9', null, true, '2019-10-18 00:00:00.000000', '5', '1875', null, 2, 2, 2);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'Automatic changover manifold for technical gases', 'ibeda_asset_gms.jpg', 'Gasmanifold-System GMS-AU', true, '2019-10-11 00:00:00.000000', 'direct I/O', 'gasversorgung', 'I/O', '68f774e4-bb9e-4cd1-8e77-744d9ad79609', null, true, '2019-10-18 00:00:00.000000', '6', '1523', null, 3, 2, 1);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'CNC-Plasma Cutting Machine', 'microstep_asset_mg.jpg', 'MG 1501.15L', true, '2019-10-11 00:00:00.000000', 'CNC', 'plasmacutter', 'SQL', '23f652de-c48b-4d5b-a5fd-bb4ea6d4d388', null, true, '2019-10-18 00:00:00.000000', '1', '1964', null, 4, 2, 1);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'intelligentes Raumluftüberwachung-System', 'ibeda_asset_airtracker.jpg', 'Airtracker Raumluftüberwachung', true, '2019-10-11 00:00:00.000000', 'Microcontroller', 'airtracker', 'MQTT', '321f2848-0d38-4a01-a65f-7e72149670a6', null, true, '2019-10-18 00:00:00.000000', '6', '1700221523', null, 10, 2, 1);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'Strahlanlage', 'roesler_asset_rrb.jpg', 'RRB 27/6-HD', true, '2017-01-01 00:00:00.000000', 'PLC S7-1500', 'blastingmachine', 'PLC', 'c553f7e2-6473-4254-8cb8-daae983fc2fc', null, true, '2018-01-01 00:00:00.000000', '1', '276', null, 6, 2, 3);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'CNC-Plasma Cutting Machine', 'microstep_asset_mcc.jpg', 'MCC 3001.15Ptk', true, '2019-10-11 00:00:00.000000', 'CNC', 'plasmacutter-mcc', 'SQL', '28dd4c50-d87a-4b2e-b6f1-4776656008b3', null, true, '2019-10-18 00:00:00.000000', '1', '2737', null, 11, 2, 1);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'Automatic changover manifold for technical gases', 'ibeda_asset_gms.jpg', 'Gasmanifold-System GMS-AU', true, '2020-06-01 00:00:00.000000', 'direct I/O', 'ibeda_gms', 'I/O', '9dff0b5a-47d5-4c58-af75-f23034171888', null, true, '2020-06-01 00:00:00.000000', '1', '123', null, 3, 2, 4);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'Gasmixer, infinitely variable', 'ibeda_asset_imixprovario.jpg', 'Gasmixer iMixproVario', true, '2020-06-01 00:00:00.000000', 'direct I/O', 'ibeda_imixprovario', 'I/O', '0c1db710-6369-4781-935f-cf886c48ab69', null, true, '2020-06-01 00:00:00.000000', '1', '123', null, 13, 2, 4);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'FlatMaster mit Walzendurchmesser 88mm und Breite 200cm', 'arku_asset_fm88.jpg', 'FlatMaster 88 200', true, '2016-05-18 00:00:00.000000', 'IPC Beckhoff', 'arku_fm88', 'OPC UA', 'b01e5204-54c9-4bc2-84d4-49a34f6d0c81', null, true, '2016-06-23 00:00:00.000000', 'IP 20', 'M644160', null, 7, 2, 5);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'Filteranlage für Feinstaub mit Rohranschluss', 'novus_asset_airline.jpg', 'Novus Airline ALG26P', true, '2019-08-01 00:00:00.000000', 'Siemens LOGO! 12/24RCEO FS04', 'novus_airline', 'PLC', '5a616907-b69b-40c5-9c9e-1dd8d2f7ee61', null, true, '2020-09-01 00:00:00.000000', '1', '202003201', null, 14, 2, 6);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'Surface Grinding Machine', 'lissmac_asset_smd.jpg', 'SMD 335 REE', true, '2020-02-01 00:00:00.000000', 'Siemens S7-1200', 'lissmac_smd', 'PLC', 'ccea6f26-7bfc-41fa-b6f5-04628e415602', null, true, '2020-02-01 00:00:00.000000', 'IP 54', 'SN026354', null, 12, 2, 7);
insert into asset (id, version, description, image_key, name, ce_certified, construction_date, control_system_type, external_id, gateway_connectivity, guid, handbook_key, has_gateway, installation_date, protection_class, serial_number, video_key, asset_series_id, company_id, room_id) values (nextval('idgen_asset'), 0, 'Surface Grinding Machine', 'lissmac_asset_sbm.jpg', 'SBM-L 1000 G1S2', true, '2019-06-01 00:00:00.000000', 'Siemens S7-1200', 'lissmac_sbm', 'PLC', 'b3324b6d-b531-4ea5-b802-18d1a2cdf115', null, true, '2019-06-01 00:00:00.000000', 'IP 54', 'SN023791', null, 8, 2, 7);



-- field_instance
---- MSF
--insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Maintenance interval', 'maintenance_interval', 'Maintenance interval', null, null, 1, 1);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Asset status', 'status', 'Asset status', null, null, 1, 2);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Cutting program', 'cutting_program', 'Cutting program', null, null, 1, 3);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Total cutting time', 'total_cutting_time', 'Total cutting time', null, null, 1, 4);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Remaining cutting time', 'remaining_cutting_time', 'Remaining cutting time', null, null, 1, 5);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Material name', 'material_name', 'Material name', null, null, 1, 6);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Material specification', 'material_specification', 'Material specification', null, null, 1, 7);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Plate thickness', 'plate_thickness', 'Plate thickness', null, null, 1, 8);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Hours till maintenance', 'hours_maintenance', 'Hours till maintenance', null, null, 1, 9);
---- ZPF
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Asset status', 'Mld_Betrieb', 'Asset status', null, null, 2, 11);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Differential pressure', 'Differenzdruck', 'Differential pressure', null, null, 2, 12);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Low pressure', 'Unterdruck', 'Low pressure', null, null, 2, 13);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Air consumption', 'Luftverbrauch', 'Air consumption', null, null, 2, 14);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Air pressure', 'Druckluft', 'Air pressure', null, null, 2, 15);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Electric current', 'Strom', 'Electric current', null, null, 2, 16);
---- MG
--insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Maintenance interval', 'maintenance_interval', 'Maintenance interval', null, null, 4, 25);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Asset status', 'status', 'Asset status', null, null, 4, 26);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Cutting program', 'cutting_program', 'Cutting program', null, null, 4, 27);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Total cutting time', 'total_cutting_time', 'Total cutting time', null, null, 4, 28);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Remaining cutting time', 'remaining_cutting_time', 'Remaining cutting time', null, null, 4, 29);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Material name', 'material_name', 'Material name', null, null, 4, 30);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Material specification', 'material_specification', 'Material specification', null, null, 4, 31);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Plate thickness', 'plate_thickness', 'Plate thickness', null, null, 4, 32);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Hours till maintenance', 'hours_maintenance', 'Hours till maintenance', null, null, 4, 33);
---- Airtracker
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Humidity', 'humidity', 'Humidity', null, null, 5, 49);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Noise', 'noise', 'Noise', null, null, 5, 50);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Dust', 'dust', 'Dust', null, null, 5, 51);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Temperature', 'temperature', 'Temperature', null, null, 5, 52);
  ---- RHB Roesler
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Asset status', 'Mld_Betrieb', 'Asset status', null, null, 6, 35);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 1 Electric current', 'Turbine1_Stromaufnahme', 'Turbine 1 Electric current', null, null, 6, 36);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 1 Rotational speed', 'Turbine1_Drehzahl', 'Turbine 1 Rotational speed', null, null, 6, 37);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 2 Electric current', 'Turbine2_Stromaufnahme', 'Turbine 2 Electric current', null, null, 6, 38);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 2 Rotational speed', 'Turbine2_Drehzahl', 'Turbine 2 Rotational speed', null, null, 6, 39);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 3 Electric current', 'Turbine3_Stromaufnahme', 'Turbine 3 Electric current', null, null, 6, 40);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 3 Rotational speed', 'Turbine3_Drehzahl', 'Turbine 3 Rotational speed', null, null, 6, 41);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 4 Electric current', 'Turbine4_Stromaufnahme', 'Turbine 4 Electric current', null, null, 6, 42);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 4 Rotational speed', 'Turbine4_Drehzahl', 'Turbine 4 Rotational speed', null, null, 6, 43);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 5 Electric current', 'Turbine5_Stromaufnahme', 'Turbine 5 Electric current', null, null, 6, 44);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 5 Rotational speed', 'Turbine5_Drehzahl', 'Turbine 5 Rotational speed', null, null, 6, 45);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 6 Electric current', 'Turbine6_Stromaufnahme', 'Turbine 6 Electric current', null, null, 6, 46);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Turbine 6 Rotational speed', 'Turbine6_Drehzahl', 'Turbine 6 Rotational speed', null, null, 6, 47);
---- MCC
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Asset status', 'status', 'Asset status', null, null, 7, 53);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Cutting program', 'cutting_program', 'Cutting program', null, null, 7, 54);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Total cutting time', 'total_cutting_time', 'Total cutting time', null, null, 7, 55);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Remaining cutting time', 'remaining_cutting_time', 'Remaining cutting time', null, null, 7, 56);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Material name', 'material_name', 'Material name', null, null, 7, 57);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Material specification', 'material_specification', 'Material specification', null, null, 7, 58);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Plate thickness', 'plate_thickness', 'Plate thickness', null, null, 7, 59);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Hours till maintenance', 'hours_maintenance', 'Hours till maintenance', null, null, 7, 60);
---- Gasversorgung
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Asset status', 'status', 'Asset status', null, null, 3, 19);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Pressure bottle left', 'pressure_bottle_left', 'Pressure bottle left', null, null, 3, 20);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Pressure bottle right', 'pressure_bottle_right', 'Pressure bottle right', null, null, 3, 21);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Pressure pipe', 'pressure_pipe', 'Pressure pipe', null, null, 3, 22);
insert into field_instance (id, version, description, external_id, name, source_sensor_label, value, asset_id, field_source_id) values (nextval('idgen_fieldinstance'), 0, 'Pressure takeoff 1', 'pressure_takeoff_1', 'Pressure takeoff 1', null, null, 3, 23);
