apiVersion: apps/v1
kind: Deployment
metadata:
  name:  <NODENAME><ID>-deployment-testsensor
  namespace: <NAMESPACE>
  labels:
    app: oisp-testsensor-sensor
spec:
  selector:
    matchLabels:
      app: oisp-testsensor-sensor
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oisp-testsensor-sensor
    spec:
      containers:
      - name: busybox
        image: docker.io/busybox:latest
        command: ["sleep"]
        args: ["100000000"]
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            value: "<NODENAME><ID>"
          - name: OISP_DEVICE_ACTIVATION_CODE
            valueFrom:
              secretKeyRef:
                name: global-devices-secret
                key: activation-code
        volumeMounts:
          - name: oisp-devices-config-volume
            mountPath: /volume/config
          - name: oisp-devices-data-volume
            mountPath: /volume/data
        image: docker.io/oisp/oisp-iot-agent:latest
      - name: fusiongatewayapp
        image: docker.io/ibn40/fusiongatewayapp:v0.3
        env:
          - name: server.port
            value: "8081"
        resources:
          limits:
        volumeMounts:
          - name: gateway-config
            mountPath: /app/resources
      - name: fusionmqttdataservice
        image: docker.io/ibn40/fusiongatewayapp:mqttv0.3 
        volumeMounts:
          - name: mqttservice-config
            mountPath: /app/resources
      volumes:
        - name: oisp-devices-config-volume
          configMap:
            name: global-devices-config
            items:
            - key: config.json
              path: config.json
        - name: gateway-config
          configMap:
            name: <NODENAME><ID>-app-config
            items:
            - key: application.yaml
              path: application.yaml
        - name: mqttservice-config
          configMap:
            name: <NODENAME><ID>-app-config
            items:
            - key: fusionmqttdataservice_application.yaml
              path: application.yaml	  
        - name: oisp-devices-data-volume
          persistentVolumeClaim:
            claimName: <NODENAME><ID>-pvc-device-data
      imagePullSecrets:
      - name: regcred
      nodeSelector:
         kubernetes.io/hostname: <NODENAME>
